# Generated by Django 4.2.6 on 2023-10-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('dispositivo', models.CharField(max_length=100)),
                ('identificacao_dispositivo', models.CharField(max_length=50)),
                ('especificacoes_tecnicas', models.TextField()),
                ('data_aquisicao', models.DateField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('tipo_dispositivo', models.CharField(choices=[('notebook', 'Notebook'), ('computador', 'Computador'), ('datashow', 'Datashow'), ('monitor', 'Monitor'), ('mesa', 'Mesa'), ('cadeira', 'Cadeira'), ('impressora', 'Impressora')], default='notebook', max_length=20)),
                ('sala', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.sala')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivo.cadastrodispositivo')),
            ],
        ),
    ]
