# Generated by Django 4.2.5 on 2023-09-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('dispositivo', models.CharField(max_length=100)),
                ('identificacao_dispositivo', models.CharField(max_length=50)),
                ('especificacoes_tecnicas', models.TextField()),
                ('data_aquisicao', models.DateField()),
            ],
        ),
    ]
