# Generated by Django 4.2.6 on 2023-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('computador', 'Computador'), ('datashow', 'Datashow'), ('monitor', 'Monitor'), ('mesa', 'Mesa'), ('cadeira', 'Cadeira'), ('impressora', 'Impressora')], default='notebook', max_length=20),
        ),
    ]
