# Generated by Django 4.2.6 on 2023-10-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva')], max_length=50)),
                ('materiais_utilizados', models.TextField()),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=20)),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('protocolo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='falha',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='falha',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='falha',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='falha',
            name='tipo_manutencao',
        ),
        migrations.AddField(
            model_name='falha',
            name='manutencao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falha.manutencao'),
        ),
    ]
