# Generated by Django 4.2.6 on 2023-10-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falha', '0002_manutencao_remove_falha_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falha',
            name='identificacao_dispositivo',
        ),
    ]
