# Generated by Django 4.2.6 on 2023-10-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falha', '0004_alter_falha_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falha',
            name='manutencao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falha.manutencao'),
        ),
    ]
