# Generated by Django 4.2.6 on 2023-10-21 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falha', '0005_alter_falha_manutencao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falha',
            name='manutencao',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='falha',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falha.falha'),
        ),
    ]
